### ISSUE TITLE
Lack of documentation 

### ISSUE THREAD

**Issue by VictorRodriguez** [serge-sans-paille/numpy-benchmarks#4]
Hi 

Thanks a lot for the benchmarks. I can run the benchmarks but these shows 3 numbers: 

 $ python run.py -t python  benchmarks/harris.py
harris Python 5431 5454 14

I can not find what does it mean or how to measure the time it takes 

Thanks a lot for the help

**Comment by serge-sans-paille** [comment]
Hi Victor, thanks for the report. Does #5 fixes your issue?

**Comment by VictorRodriguez** [comment]
Yes , thanks a lot

**Comment by serge-sans-paille** [comment]
Out of curiosity: what kind of benchmarks are you leading?

**Comment by VictorRodriguez** [comment]
Can I work in a summary ? in order to generate one number. The idea is to merge this benchmark in openbenchamarking.org ( with all the credits to authors ) What do you think ? @serge-sans-paille

**Comment by VictorRodriguez** [comment]
I want to measure the implementation we did ( in clearlinux.org ) of the OPENBLAS with AVX2 . in order to use the AVX registers
